export const ADD_A_PRODUCT = "ADD_A_PRODUCT";
export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const EDIT_PRODUCT_STARTED = "EDIT_PRODUCT_STARTED";
export const EDIT_PRODUCT_SUCCESSFUL = " EDIT_PRODUCT_SUCCESSFUL";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_CART_PRODUCTS = "FETCH_CART_PRODUCTS";
